include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    iterable_contains_unrelated_type: error
    always_declare_return_types: warning

linter:
  rules:
    - use_super_parameters
    - use_decorated_box
    - use_colored_box
    - require_trailing_commas
    - prefer_relative_imports
    - directives_ordering
    - always_declare_return_types
