name: temopedia
description: A new Flutter project.
publish_to: none
version: 1.2.3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_speed_dial: ^6.0.0
  fpdart: ^0.2.0
  get_it: ^7.2.0
  go_router: ^4.4.1
  logger: ^1.1.0
  path_provider: ^2.0.11
  rxdart: ^0.27.5
  shimmer: ^2.0.0
  temtem_api_wrapper:
    git:
      url: https://github.com/TesteurManiak/temtem_api_wrapper.git
      ref: 0.2.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.9
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/icon.png"

flutter_native_splash:
  color: "#1f183a"
  image: "assets/splash/splash.png"
  web: false
  android: true
  ios: true
  android_12:
    image: "assets/splash/android_12_splash.png"
    color: "#1f183a"
    icon_background_color: "#1f183a"

flutter:
  uses-material-design: true
  assets:
    - assets/
