name: temopedia
description: A new Flutter project.

version: 1.2.3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  flutter_speed_dial: ^1.2.5
  sqflite: ^1.3.1+1
  cached_network_image: ^2.3.1
  temtem_api_wrapper: ^0.1.1+3
  rxdart: ^0.24.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

