name: temopedia
description: A new Flutter project.
publish_to: none
version: 2.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  clock: ^1.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1
  go_router: ^9.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1
  shimmer: ^3.0.0
  theme_tailor_annotation: ^2.0.0

dev_dependencies:
  alchemist: ^0.6.1
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  fd_lints: ^2.0.1
  flutter_gen: ^5.3.1
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  go_router_builder: ^2.2.2
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  theme_tailor: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/icon.png"
  image_path_ios: "assets/launcher_icon/icon_ios.png"

flutter_native_splash:
  color: "#1f183a"
  image: "assets/flutter_native_splash/splash.png"
  web: false
  android: true
  ios: true
  android_12:
    image: "assets/flutter_native_splash/android_12_splash.png"
    color: "#1f183a"
    icon_background_color: "#1f183a"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/illustrations/
    - assets/icons/
    - assets/logos/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
