name: temopedia
description: A new Flutter project.
publish_to: none
version: 2.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  clock: ^1.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  freezed_annotation: ^2.2.0
  go_router: ^6.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.8.0
  shimmer: ^2.0.0

dev_dependencies:
  alchemist: ^0.6.0
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  flutter_gen_runner: ^5.2.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  go_router_builder: ^1.1.7
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1
  riverpod_lint: ^1.1.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/icon.png"

flutter_native_splash:
  color: "#1f183a"
  image: "assets/flutter_native_splash/splash.png"
  web: false
  android: true
  ios: true
  android_12:
    image: "assets/flutter_native_splash/android_12_splash.png"
    color: "#1f183a"
    icon_background_color: "#1f183a"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/illustrations/
    - assets/icons/
    - assets/logos/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
