name: temopedia
description: A new Flutter project.
publish_to: none
version: 1.2.3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_speed_dial: ^5.1.0
  rxdart: ^0.27.3
  sqflite: ^2.0.2
  temtem_api_wrapper:
    git:
      url: https://github.com/TesteurManiak/temtem_api_wrapper.git
      ref: master

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
