name: temopedia
description: A new Flutter project.
publish_to: none
version: 1.2.3

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  flutter_speed_dial: ^6.2.0
  freezed_annotation: ^2.2.0
  go_router: ^6.5.0
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/icon.png"

flutter_native_splash:
  color: "#1f183a"
  image: "assets/splash/splash.png"
  web: false
  android: true
  ios: true
  android_12:
    image: "assets/splash/android_12_splash.png"
    color: "#1f183a"
    icon_background_color: "#1f183a"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/splash/splash.png
