name: temopedia
description: A new Flutter project.

version: 1.0.1+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  cached_network_image: ^2.0.0
  flutter_launcher_icons: ^0.7.4
  flutter_speed_dial: ^1.2.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Temopedia
      fonts:
        - asset: fonts/Temopedia.ttf
