name: temopedia
description: A new Flutter project.
publish_to: none
version: 1.2.3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_speed_dial: ^6.0.0
  get_it: ^7.2.0
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0
  path_provider: ^2.0.11
  rxdart: ^0.27.5
  temtem_api_wrapper:
    git:
      url: https://github.com/TesteurManiak/temtem_api_wrapper.git
      ref: master

dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^2.5.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
