/// Flutter icons Temopedia
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Temopedia
///      fonts:
///       - asset: fonts/Temopedia.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Temopedia {
  Temopedia._();

  static const _kFontFam = 'Temopedia';

  static const IconData sort_name_up = const IconData(0xf15d, fontFamily: _kFontFam);
  static const IconData sort_number_up = const IconData(0xf162, fontFamily: _kFontFam);
}
